FROM imagen base para el build
ARG JAR_FILE= direccion donde va a estar el archivo jar
COPY copia del jar anterior y el nombre que deseemos
EXPOSE puerto
ENTRYPOINT aca especificamos que utilizamos para ejecutar, que tipo de archivo es y el nombre que usamos en COPY